import { Knex } from 'knex'

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex('app_private.transaction').del()

  // Inserts seed entries
  await knex('app_private.transaction').insert([
    {
      id: 1,
      posted: knex.fn.now(),
      amount: -60000,
      type: 'Email Trfs1',
      name: 'Checking',
      memo: 'E-TRANSFER RECEIVED',
      bank_transaction_id: '452346',
      account_id: 1,
      category_id: null,
    },
    {
      id: 2,
      posted: knex.fn.now(),
      amount: 10000,
      type: 'Email Trfs2',
      name: 'Checking',
      memo: 'E-TRANSFER RECEIVED',
      bank_transaction_id: '459876',
      account_id: 1,
      category_id: null,
    },
    {
      id: 3,
      posted: knex.fn.now(),
      amount: 5000,
      type: 'Email Trfs3',
      name: 'Checking',
      memo: 'E-TRANSFER RECEIVED',
      bank_transaction_id: '4234556',
      account_id: 1,
      category_id: null,
    },
    {
      id: 4,
      posted: knex.fn.now(),
      amount: -30000,
      type: 'Email Trfs4',
      name: 'Checking',
      memo: 'E-TRANSFER RECEIVED',
      bank_transaction_id: '450696',
      account_id: 2,
      category_id: null,
    },
    {
      id: 5,
      posted: knex.fn.now(),
      amount: -500,
      type: 'Email Trfs5',
      name: 'Checking',
      memo: 'E-TRANSFER RECEIVED',
      bank_transaction_id: '453456',
      account_id: 2,
      category_id: null,
    },
    {
      id: 6,
      posted: knex.fn.now(),
      amount: -600,
      type: 'Email Trfs6',
      name: 'Checking',
      memo: 'E-TRANSFER RECEIVED',
      bank_transaction_id: '48756',
      account_id: 2,
      category_id: null,
    },
    {
      id: 7,
      posted: knex.fn.now(),
      amount: -700,
      type: 'Email Trfs7',
      name: 'Checking',
      memo: 'E-TRANSFER RECEIVED',
      bank_transaction_id: '456756',
      account_id: 3,
      category_id: null,
    },
    {
      id: 8,
      posted: knex.fn.now(),
      amount: -800,
      type: 'Email Trfs8',
      name: 'Checking',
      memo: 'E-TRANSFER RECEIVED',
      bank_transaction_id: '476556',
      account_id: 3,
      category_id: null,
    },
    {
      id: 9,
      posted: knex.fn.now(),
      amount: -900,
      type: 'Email Trfs9',
      name: 'Checking',
      memo: 'E-TRANSFER RECEIVED',
      bank_transaction_id: '4567',
      account_id: 3,
      category_id: null,
    },
  ])
}
