mutation UpsertBankAccount($accountId: Int!, $type: String!, $currency: String!, $bankAccountId: String!) {
  upsertBankAccount(
    input: { bankAccount: { accountId: $accountId, type: $type, currency: $currency, bankAccountId: $bankAccountId } }
  ) {
    bankAccount {
      ...BankAccountFragment
    }
  }
}

mutation UpsertBankAccountReconciliation($bankAccountId: Int!, $balance: BigInt!, $asOf: Datetime!) {
  upsertBankAccountReconciliation(
    input: { bankAccountReconciliation: { bankAccountId: $bankAccountId, balance: $balance, asOf: $asOf } }
  ) {
    bankAccountReconciliation {
      ...BankAccountReconciliationFragment
    }
  }
}

mutation UpdateBankAccountName($id: Int!, $accountId: Int!, $name: String!) {
  upsertBankAccount(input: { bankAccount: { name: $name, accountId: $accountId } }, where: { id: $id }) {
    bankAccount {
      ...BankAccountFragment
    }
  }
}

mutation UpdateBankAccountClosed($id: Int!, $accountId: Int!, $closed: Boolean!) {
  upsertBankAccount(input: { bankAccount: { closed: $closed, accountId: $accountId } }, where: { id: $id }) {
    bankAccount {
      ...BankAccountFragment
    }
  }
}
