query GetBankCsvDefinitions($accountId: Int!) {
  allBankCsvDefinitions(filter: { accountId: { equalTo: $accountId } }) {
    nodes {
      ...BankCsvDefinitionFragment
    }
  }
}

mutation CreateBankCsvDefinition($accountId: Int!, $name: String!, $mapping: JSON!, $bankAccountId: Int) {
  createBankCsvDefinition(
    input: { bankCsvDefinition: { accountId: $accountId, name: $name, mapping: $mapping, bankAccountId: $bankAccountId } }
  ) {
    bankCsvDefinition {
      ...BankCsvDefinitionFragment
    }
  }
}

mutation UpdateBankCsvDefinition($nodeId: ID!, $name: String, $mapping: JSON, $bankAccountId: Int) {
  updateBankCsvDefinition(
    input: { nodeId: $nodeId, bankCsvDefinitionPatch: { name: $name, mapping: $mapping, bankAccountId: $bankAccountId } }
  ) {
    bankCsvDefinition {
      ...BankCsvDefinitionFragment
    }
  }
}

mutation DeleteBankCsvDefinitionById($id: Int!) {
  deleteBankCsvDefinitionById(input: { id: $id }) {
    deletedBankCsvDefinitionId
  }
}

query GetTransactionsForCsvAccountMatching($filter: TransactionFilter!) {
  allTransactions(filter: $filter) {
    nodes {
      id
      bankAccountId
      bankTransactionId
      amount
      originalAmount
      posted
      originalPosted
    }
  }
}
