query GetCategories($accountId: Int!) {
  allCategories(filter: { accountId: { equalTo: $accountId } }) {
    nodes {
      ...CategoryFragment
    }
  }
}

mutation CreateCategory($accountId: Int!, $name: String, $regex: String) {
  createCategory(input: { category: { accountId: $accountId, name: $name, regex: $regex } }) {
    category {
      ...CategoryFragment
    }
  }
}

mutation UpdateCategory($nodeId: ID!, $name: String, $regex: String) {
  updateCategory(input: { nodeId: $nodeId, categoryPatch: { name: $name, regex: $regex } }) {
    category {
      ...CategoryFragment
    }
  }
}

mutation DeleteCategoryById($id: Int!) {
  deleteCategoryById(input: { id: $id }) {
    deletedCategoryId
  }
}
